### ISSUE TITLE
Make color customizable

### ISSUE THREAD

**Issue by maku** [tobszarny/ActiveTabHighlighterPlugin#2]
I tried the plugin and really appreciate the effort developing it. 

But I am not able to use it. 
With the current color this does not work. I am using the "Default" Theme as my base scheme and it looks not so good...

**Comment by tobszarny** [comment]
Working on it.

**Comment by tobszarny** [comment]
First customization capabilities delivered

**Comment by k3n** [comment]
Thanks for this!

It can be found under `Tools > Active Tab Highlighter Plugin` for anyone curious.

**Comment by Sinapse87** [comment]
I do not have that menu in Tools, unfortunately.

**Comment by tobszarny** [comment]
It is on File/Settings... then Tools from left sidepanel. Hope it helps

**Comment by pwuk** [comment]
Nice, thanks!
