### ISSUE TITLE
Plugin version (1.5.0) is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92

### ISSUE THREAD

**Issue by jacobhanson1010** [tobszarny/ActiveTabHighlighterPlugin#21]
Hey, downloaded the latest release, but IntelliJ does not permit it to be installed with my build.

![Untitled](https://user-images.githubusercontent.com/9847347/129263834-7e9ae2d4-d9af-4f19-8965-124977855e5e.png)

**Comment by jacobhanson1010** [comment]
I see the problem, your `activetabhighlighter-1.5.0.jar` file on the releases page has:
`<idea-version since-build="211.7628" until-build="211.*" />`
Whereas the source has `<idea-version since-build="162.539.11"/>`. Why is that?

**Comment by schittli** [comment]
Good evening

Maybe this information helps about the IntelliJ Release which can not install activetabhighlighter-1.5.0.jar

```
IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64

```
Thanks a lot for your great work!
kind regards,
Thomas

**Comment by jacobhanson1010** [comment]
https://github.com/tobszarny/ActiveTabHighlighterPlugin/pull/22/files

This change is what we need! It prevents the since-build / until-build fields from being overwritten by the patchPluginXml gradle task.

**Comment by tobszarny** [comment]
Fixed
