### ISSUE TITLE
When will 2.0 be released

### ISSUE THREAD

**Issue by sdhzwc** [tobszarny/ActiveTabHighlighterPlugin#27]

**Comment by tobszarny** [comment]
Yes, adapting to IDEA API changes.

**Comment by sdhzwc** [comment]
> Yes, adapting to IDEA API changes.

When will the latest version be released and I want to experience the latest features😂

**Comment by tobszarny** [comment]
[2.0.1](https://github.com/tobszarny/ActiveTabHighlighterPlugin/releases/tag/2.0.1-RELEASE) is out
