### ISSUE TITLE
No effect with RubyMine 2017.1 EAP

### ISSUE THREAD

**Issue by Justin-Maxwell** [tobszarny/ActiveTabHighlighterPlugin#3]
Didn't seem to change anything in RubyMine w/Darcula...

Others coming here might want to vote-up https://youtrack.jetbrains.com/issue/IDEA-126775

There might be some value in working with https://plugins.jetbrains.com/plugin/9377-material-theme-ui-fork to incorporate active-tab customisation as part of that, cos it's dark, and quite nice, except that the active-tab thumb-indicator is even less visible than with Darcula.

**Comment by s001dxp** [comment]
Doesn't seem to work in PhpStorm either

**Comment by tobszarny** [comment]
Now supports all IntelliJ branch 145.0+ based products
