### ISSUE TITLE
Provide Settings support for unfocused Tab color

### ISSUE THREAD

**Issue by stohn777** [tobszarny/ActiveTabHighlighterPlugin#49]
Is the less-intense, unfocused Tab color intentional (screenshot below)?  I prefer the default, unfocused Tab color.  Could this be an option within the plugin's settings?

OS: Ubuntu 23.

Thanks.

![image](https://github.com/tobszarny/ActiveTabHighlighterPlugin/assets/38730299/84aa492f-f723-4907-b2be-2620868ef127)

**Comment by tobszarny** [comment]
Hi, this is a bug. Most likely some race condition. I'll look into it.

**Comment by tobszarny** [comment]
@stohn777 Could you provide steps to replicate or describe the conditions of this problem manifesting?

**Comment by stohn777** [comment]
Interestingly and perhaps related to your earlier comment about being a race condition, cannot duplicate today.  If it recurs, I'll provide you with some details.

Will close.
